### ISSUE TITLE
笔记图片缺失的问题

### ISSUE THREAD

**Issue by Ameftn14** [yile-liu/ZJU_database_system#1]
非常感谢学长的分享，您的数据库系统笔记非常好！有点小问题就是，您的markdown笔记中的图片地址似乎在本地，因此无法查看内容；如果您有空的话，或许导出pdf进行上传是一种解决方案。再次感谢学长为同学们课程学习带来的帮助！

**Comment by yile-liu** [comment]
已经修复，现在可以在github上直接查看带图片的markdown。（PDF这种不能编辑的文件格式不符合开源精神
